export const CITIES = [
  'London', 'Paris', 'New York', 'Tokyo', 'Sydney', 'Dubai', 'Singapore', 
  'Rome', 'Barcelona', 'Amsterdam', 'Berlin', 'Moscow', 'Istanbul', 'Bangkok',
  'Seoul', 'Mumbai', 'Cairo', 'Rio de Janeiro', 'Cape Town', 'Toronto', 
  'Los Angeles', 'San Francisco', 'Chicago', 'Mexico City', 'Lagos', 'Buenos Aires',
  'São Paulo', 'Jakarta', 'Hong Kong', 'Beijing', 'Manila', 'Kuala Lumpur',
  'Lima', 'Santiago', 'Caracas', 'Melbourne', 'Abu Dhabi', 'Dallas', 'Houston', 
  'Philadelphia', 'Milan', 'Copenhagen', 'Zurich', 'Vienna', 'Brussels', 'Oslo', 
  'Madrid', 'Athens', 'Stockholm', 'Geneva', 'Budapest', 'Riyadh', 'Doha', 
  'Kuwait City', 'Jeddah', 'Tehran', 'Amman', 'Johannesburg', 'Accra', 'Nairobi', 
  'Dar es Salaam', 'Antananarivo', 'La Paz', 'Sucre', 'Santa Cruz', 'Asunción',
  'Montevideo', 'Antofagasta', 'Mendoza', 'Quito', 'Guayaquil', 'Arequipa',
  'Bucharest', 'Belgrade', 'Sarajevo', 'Skopje', 'Podgorica', 'Zagreb', 'Split',
  'Ljubljana', 'Sofia', 'Chisinau', 'Porto Alegre', 'Belo Horizonte', 'Curitiba', 
  'Porto', 'Braga', 'Funchal', 'Viana do Castelo', 'Malaga', 'Alicante', 'Sevilla', 
  'Granada', 'Valencia', 'Marbella', 'Ibiza', 'Cordoba', 'Palma', 'Salamanca', 
  'Córdoba', 'Santiago de Compostela', 'Gijón', 'Badajoz', 'Oviedo', 'Almeria', 
  'Murcia', 'Teruel', 'Las Palmas de Gran Canaria', 'Santander', 'Valladolid', 
  'Alicante', 'Albacete', 'Toledo', 'Reus', 'Girona', 'León', 'Cuenca', 'Lugo', 
  'Jerez', 'La Coruña', 'Logroño', 'Huesca', 'Cádiz', 'Gandía', 'Castellón', 
  'Marbella', 'Torremolinos', 'Zaragoza', 'Salamanca', 'Lugo', 'A Coruña', 'Córdoba', 
  'La Rioja', 'Soria', 'San Sebastián', 'Santander', 'Cádiz', 'Punta Cana', 'Miami', 
  'Las Vegas', 'Portland', 'Seattle', 'San Diego', 'Boston', 'Denver', 'Salt Lake City', 
  'Tampa', 'Orlando', 'Dallas', 'Phoenix', 'Austin', 'Detroit', 'Indianapolis', 'Nashville', 
  'Columbus', 'Cincinnati', 'Raleigh', 'Pittsburgh', 'Baltimore', 'Richmond', 'Minneapolis', 
  'St. Louis', 'Kansas City', 'New Orleans', 'Memphis', 'Milwaukee', 'Buffalo', 'Sacramento',
  'Oklahoma City', 'Louisville', 'Fresno', 'Tucson', 'Long Beach', 'Oakland', 'Bakersfield', 
  'Anaheim', 'Stockton', 'Chula Vista', 'Chandler', 'Lubbock', 'Chesapeake', 'Scottsdale', 
  'Glendale', 'Gilbert', 'Huntington Beach', 'Montgomery', 'Mobile', 'Shreveport', 'Fayetteville',
  'Arlington', 'Gilbert', 'Boulder', 'Grand Rapids', 'Waco', 'Brownsville', 'Midland', 'Huntsville', 
  'Laredo', 'Odessa', 'Macon', 'Cedar Rapids', 'Topeka', 'Naperville', 'Denton', 'Boulder', 
  'Gainesville', 'Spokane', 'Cedar Rapids', 'Peoria', 'Lafayette', 'Bend', 'Billings', 'Boise',
  'Eugene', 'Springfield', 'Fargo', 'Missoula', 'Great Falls', 'Rapid City', 'Medford', 'Beaverton',
  'Corvallis', 'Lakewood', 'Richland', 'Yakima', 'Syracuse', 'Wilmington', 'Dayton', 'Charleston', 
  'Newport News', 'Mobile', 'Grand Prairie', 'Odessa', 'Palm Bay', 'Sunrise', 'Shreveport', 'Killeen', 
  'Rockford', 'Simi Valley', 'Tallahassee', 'Oxnard', 'Columbia', 'Sterling Heights', 'Hartford', 
  'Vallejo', 'Allentown', 'Wichita', 'Vancouver'
] as const;

export const BATCH_SIZE = 6;